server:
  port: 8089
spring:
  cache:
    type: redis
  redis:
    host: 192.168.99.101
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: satya
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true


      
